In [9]:
import jax
from jax import numpy as jnp

In [119]:
ref = jnp.array([[1, 0, 0],
                 [0, 2, 0],
                 [0, 0, 3],
                 [1, 1, 1]])

x = jnp.array([1, 1, 1])
ref_norm = jnp.linalg.norm(ref, axis=1)
jnp.linalg.norm(jnp.cross(x, ref), axis=1) / ref_norm

Array([1.4142135, 1.4142135, 1.4142135, 0.       ], dtype=float32)

In [73]:
x = jnp.array([[3, 2, 1],
               [1, 2, 3],
               [3, 2, 3],
               [7, 7, 7]])
y = jnp.array([3, 0, 1, 1])

idx = jnp.argsort(y)
# x = jnp.take_along_axis(x, idx[:, None], axis=0)

x[idx]

Array([[1, 2, 3],
       [3, 2, 3],
       [7, 7, 7],
       [3, 2, 1]], dtype=int32)

In [138]:
x = jnp.array([1, 2, 3, 2, 0, 1])

jnp.argmin(x)

x = x.at[0].set(jnp.argmin(x))

jnp.full((5, 3), jnp.nan)

Array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]], dtype=float32, weak_type=True)

In [ ]:
# weight = jnp.full((self.n_objs, self.n_objs), 1e-6) + jnp.eye(self.n_objs)
# asf = weight @ merged_fitness.T
# extreme = asf